# NOTE: We use ingress here rather than a simple service so we can route traffic
#   based on hostname and not only IP. Ingress also has the advantage of being
#   able to serve TLS.
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gpupoet-app-ingress
spec:
  # patched in kustomize for TLS in production
  rules:
    - host: gpupoet.local
      http:
        paths:
          # Allow all traffic to the app
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app
                port:
                  name: web-ui
