apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gpupoet-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patch-app-development.yaml
    target:
      kind: Deployment
      name: app

secretGenerator:
  - name: app-creds
    envs:
      - .env.dev.app
  - name: db-creds
    envs:
      - .env.dev.db

images:
  - name: gpupoet-image-app
    newName: gpupoet-dev
    newTag: latest
  - name: gpupoet-image-db
    newName: postgres
    newTag: "15-alpine"
