apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gpupoet-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patch-app-development.yaml
    target:
      kind: Deployment
      name: app
  # Override ingress host for local development
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: gpupoet.local
      # Remove the /ops/revalidate-cache blocking rule for dev (allows manual testing)
      - op: remove
        path: /spec/rules/0/http/paths/0
    target:
      kind: Ingress
      name: gpupoet-app-ingress
  # Override storageClassName for minikube
  - patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: standard
    target:
      kind: StatefulSet
      name: db
  # Remove IndexNow CronJob (not needed in dev)
  - patch: |-
      $patch: delete
      apiVersion: batch/v1
      kind: CronJob
      metadata:
        name: indexnow-notifier
    target:
      kind: CronJob
      name: indexnow-notifier
  # Remove IndexNow PVC (not needed in dev)
  - patch: |-
      $patch: delete
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: indexnow-pvc
    target:
      kind: PersistentVolumeClaim
      name: indexnow-pvc

secretGenerator:
  - name: app-creds
    envs:
      - .env.dev.app
  - name: db-creds
    envs:
      - .env.dev.db

images:
  - name: gpupoet-image-app
    newName: gpupoet-dev
    newTag: latest
  - name: gpupoet-image-db
    newName: postgres
    newTag: "15-alpine"
