apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gpupoet-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patch-app-development.yaml
    target:
      kind: Deployment
      name: app
  # Override ingress host for local development
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: gpupoet.local
      # Remove the /ops/revalidate-cache blocking rule for dev (allows manual testing)
      - op: remove
        path: /spec/rules/0/http/paths/0
    target:
      kind: Ingress
      name: gpupoet-app-ingress
  # Override storageClassName for minikube
  - patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: standard
    target:
      kind: StatefulSet
      name: db
  # IndexNow: Use standard storage class for minikube PVC
  - patch: |-
      - op: replace
        path: /spec/storageClassName
        value: standard
      - op: remove
        path: /spec/volumeName
    target:
      kind: PersistentVolumeClaim
      name: indexnow-pvc
  # IndexNow: Use local sitemap URL for dev
  - patch: |-
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/1/value
        value: "http://app:3000/sitemap.xml"
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/2/value
        value: "localhost:3000"
    target:
      kind: CronJob
      name: indexnow-notifier

secretGenerator:
  - name: app-creds
    envs:
      - .env.dev.app
  - name: db-creds
    envs:
      - .env.dev.db

images:
  - name: gpupoet-image-app
    newName: gpupoet-dev
    newTag: latest
  - name: gpupoet-image-db
    newName: postgres
    newTag: "15-alpine"
  - name: indexnow-notifier-image-placeholder
    newName: indexnow-notifier-dev
    newTag: latest
